### ISSUE TITLE
Polyfill libraries

### ISSUE THREAD

**Issue by SimenB** [deepsweet/autopolyfiller-loader#11]
How do I polyfill libraries from `node_modules`? If I don't exclude `node_modules` from the loader, the whole thing explodes.

**Comment by deepsweet** [comment]
use `include` instead of `exclude`? [it can be an array too](https://webpack.github.io/docs/configuration.html#module-loaders).

**Comment by SimenB** [comment]
Hmm, OK, I was hoping you knew of a clean way to do it. This seems to work fine.

```js
    postLoaders: [
      {
        test: /\.js$/,
        exclude: [ /-loader/, /webpack/ ],
        loader: 'autopolyfiller',
        query: { browsers: [ 'last 2 versions', 'IE >= 8', 'Chrome >= 33' ] }
      }
    ]
```
