### ISSUE TITLE
Error: Cannot find module 'polyfill-service/polyfills/Window.prototype.base64/polyfill'

### ISSUE THREAD

**Issue by chrisjbrown** [deepsweet/autopolyfiller-loader#15]
I'm using btoa that should be provided by polyfill-service through the atob/polyfill but it seems to be incorrectly be looking for window.prototype.base64

```
ERROR in ./src/js/utils/dbk.utils.common.js
Module build failed: Error: Cannot find module 'polyfill-service/polyfills/Window.prototype.base64/polyfill'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/deBijenkorf/Sites/responsive-assets/node_modules/autopolyfiller-loader/index.js:23:59
    at Array.forEach (native)
    at Object.module.exports (/Users/deBijenkorf/Sites/responsive-assets/node_modules/autopolyfiller-loader/index.js:22:19)
 @ ./src/js/dbk.form.js 19:22-60
Warning: Task "webpack:dev" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by franciclo** [comment]
I'm having a similar issue, building my app with webpack in Visual Studio 2015, and a bunch of errors about not finding "polyfill-service/polyfills/Windows.prototype.base64/polyfill" or "polyfill-service/polyfills/Windows.prototype.matchMedia/polyfill"
The same setup is working ok in ubuntu

**Comment by deepsweet** [comment]
https://github.com/deepsweet/autopolyfiller-loader/issues/17

**Comment by NumminorihSF** [comment]
Is this issue still actual? Try on v1.0.0
