### ISSUE TITLE
maintainer needed

### ISSUE THREAD

**Issue by deepsweet** [deepsweet/autopolyfiller-loader#17]
hey. does anyone want (and can) to maintain this package?

**Comment by okonet** [comment]
I'd vote for @azproduction since he owns almost all `autopolyfiller-` repos. Please???

**Comment by deepsweet** [comment]
ofc if Mikhail wants to 👐  I'm really out of scope here so I can't even merge some PRs because I don't use autopolyfiller anymore and can't test it IRL. autopolyfiller-loader has 604 downloads in the last month, so someone should be able to take it and care for it 😃

**Comment by NumminorihSF** [comment]
If nobody else wants, I can

**Comment by deepsweet** [comment]
done, you should accept an invitation to get push access to the repository. just let me know when you will have something to publish.

**Comment by NumminorihSF** [comment]
@deepsweet can you add me to npms collaborators? please push tag v0.4.1 to npm

**Comment by deepsweet** [comment]
@NumminorihSF 

```
$ npm owner ls autopolyfiller-loader
deepsweet <kir@soulshine.in>
numminorihsf <numminorihsf@gmail.com>
```
