### ISSUE TITLE
Add support for webpack 2.0 (beta)

### ISSUE THREAD

**Issue by leesiongchan** [deepsweet/autopolyfiller-loader#20]

**Comment by NumminorihSF** [comment]
Hi. I checked how it works with webpack 2. The only problem is that autopolyfiller's parser can't parse ES6+. I'll append another parser's version to autopolyfiller, to allow loader use es6.

**Comment by NumminorihSF** [comment]
Please try v1.1.0. If it has any problem - reopen this issue.

**Comment by prontiol** [comment]
I am unable to make it work.
Here what I get:
```
ERROR in ./src/js/module/index.js
Module build failed: Error: Final loader didn't return a Buffer or String
```
I use the following config with webpack 2.2.1:
```
rules: [{
      enforce: 'post',
      test: /\.js$/,
      exclude: /\/(node_modules|bower_components)\//,
      loader: 'autopolyfiller',
      query: {
        browsers: ['last 2 versions', 'ie >= 9'],
        parserOptions: { ecmaVersion: 6 },
      },
    }],
```
Can someone advise?

**Comment by NumminorihSF** [comment]
@prontiol, does you use sourcemaps? if you are using it, can you try build app without sourcemaps?

**Comment by prontiol** [comment]
I don't.

**Comment by NumminorihSF** [comment]
Oh, I did not see it earlier, but in webpack 2 you can't use `autopolyfiller`, it enforce you to use `autopolyfiller-loader`.
