### ISSUE TITLE
Feature request: Add ability to add custom polyfills trough webpack.config

### ISSUE THREAD

**Issue by okonet** [deepsweet/autopolyfiller-loader#3]
Something like:

```
module.exports = {
  autopolyfiller: {
    // Your custom config here
  }
};
```

This object can be then accessed in the loader.

**Comment by deepsweet** [comment]
https://github.com/deepsweet/autopolyfiller-loader/issues/17

**Comment by NumminorihSF** [comment]
Use `use` key in query (v0.4.1+). Example is in readme.
